### ISSUE TITLE
website doesn't show 404

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#100]
**Describe the bug**
When opening the site on a URL that doesn't exist (anymore), the 404 page is not shown, but the page keeps on loading forever..

**To Reproduce**
1. Open this url: `http://tilburgsciencehub.com/i/do/not/exist`

**Expected behavior**
404 page should be shown.

**Screenshots**
<img width="779" alt="image" src="https://user-images.githubusercontent.com/16557730/109665402-6a00fa00-7b6e-11eb-8e4b-5d0e14bf0589.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari

**Comment by andreantonacci** [comment]
I think this is due to the fact that we do not have a unique overview page for each hierarchy level (see issue #106).

So, to have each link in the breadcrumb to work, I think you added this in the 404 page:
![image](https://user-images.githubusercontent.com/50109671/112284358-723de800-8c89-11eb-8005-adbfea3ebc71.png)

However, when a proper 404 page must be served now (for instance the user clicks on an old/invalid URL), it enters into a loop.

We need a proper, styled 404 page that works every time.

**Comment by heyarviind** [comment]
I removed the js code, need to test it after https://github.com/tilburgsciencehub/website/pull/158 PR get merged

**Comment by andreantonacci** [comment]
#158 merged
