### ISSUE TITLE
Accessibility Problem with 'Loss Functions and Cost Functions' Article

### ISSUE THREAD

**Issue by K-sohooli** [tilburgsciencehub/website#1174]
There are two problems with 'Loss Functions and Cost Functions' Article:

1- The article titled "Loss Functions and Cost Functions in Machine Learning" has been merged. Although the title appears on the "Machine Learning and Predictive Modeling" page, it isn't hyperlinked. However, users can still access the article by searching for it using the search bar.

2- None of the images in the article are displayed.

**Comment by krzysztof99xd** [comment]
Hey @K-sohooli, thanks for noticing.
The issue arose because of the wrong directory structure.  Every subcategory needs to have a folder with `_index.md` file which specifies that it is a subcategory and furthermore, the correct weight needs to be assigned to it.

The problem with pictures is also related to where the pictures are in the folders. 

I will discuss with you on Teams how we can fix it.
