### ISSUE TITLE
Broken links popular pages

### ISSUE THREAD

**Issue by valerievossen** [tilburgsciencehub/website#1209]
Hi @krzysztof99xd, 

I noticed most of the popular pages links are broken, or linking to a wrong page. These are suggested when you click the "Search" button. I attached a picture to show what I mean (I couldn't make a screenshot as this changed the suggested pages haha). I don't know where to find these links, that's why I made an issue, but let me know if I can help!

![WhatsApp Image 2024-06-11 at 12 56 36](https://github.com/tilburgsciencehub/website/assets/127310459/d19885d9-ff8f-474f-9fc2-054603f6295f)

**Comment by krzysztof99xd** [comment]
Hey Valerie,
Thank you for noticing. 
I will take a look at it!

**Comment by krzysztof99xd** [comment]
I took a look at the issue. I believe that the problem lies with incorrect aliases for every page. In Hugo, aliases are used to create alternative URLs for a piece of content. 
When I click on some popular pages that show up from the search tab, they go to incorrect aliases (old URLs I believe). 

I was checking for some pages what happens when I paste a correct alias taken directly from MD file and everything seems to work (both locally and on the live website). For example when we click on Use ChatGPT for your research article one of the aliases is -> `/topics/more-tutorials/chatgpt-article/chat-gpt-research/`  but it tries to redirect us to -> `topics/more-tutorials/chatgpt-article/chat-gpt-research/` which is an incorrect link. This link appears inside `pages.json`. I fixed it and the other links there but I am not sure if this solves the whole problem since I can see that there is a GitHub action set up to fetch the popular pages.

If you @thierrylahaije were working on it, could you maybe share some insights with us or take over the issue if you know how to fix it?

Thanks in advance!

**Comment by thierrylahaije** [comment]
Hi @krzysztof99xd,

As far as I can currently see, this is not an issue we should worry about. This issue will automatically be fixed when we have the new solution for the popular pages, since the content of these popular pages is currently filled from pages.json, and in the future should be fixed from matomo or inside statistics. Furthermore, the only problem I had with the current pages was that it always had a '/' at the end of the link, which we could remove. This is an easy fix that you can do within the pages.json for now.

**Comment by thierrylahaije** [comment]
> Hi @krzysztof99xd,
> 
> As far as I can currently see, this is not an issue we should worry about. This issue will automatically be fixed when we have the new solution for the popular pages, since the content of these popular pages is currently filled from pages.json, and in the future should be fixed from matomo or inside statistics. Furthermore, the only problem I had with the current pages was that it always had a '/' at the end of the link, which we could remove. This is an easy fix that you can do within the pages.json for now.

Don't worry about this issue, I updated the pages.json so now all links are working, the update is available in my PR. When we have the new source for popular pages, we need to adjust this.
