### ISSUE TITLE
MATLAB install page links to UZH

### ISSUE THREAD

**Issue by rgreminger** [tilburgsciencehub/website#123]
**Describe the bug**
The following page refers to the UZH license and links to a broken UZH page: 
https://tilburgsciencehub.com/building-blocks/configure-your-computer/statistics-and-computation/matlab/

**Expected behavior**
Should point to working installation instructions for TiU (I think this was actually the case in the old page)

**Comment by andreantonacci** [comment]
Hi Rafael, thanks for noticing this. I think the old page linked to the same broken URL (see here: https://github.com/tilburgsciencehub/deprecated-website/blob/tilburg-update/docs/setup/matlab.md).

Do you know where I can find the instructions for TiU? (No intranet, so that external users can see the page anyway)
Thanks

**Comment by rgreminger** [comment]
Hi Andrea, 
Just checked and it's possible that the old page was using this file (Matlab combined with other programming languages): 
https://github.com/tilburgsciencehub/deprecated-website/blob/tilburg-update/docs/setup/otherProgLang.md

Though there the link points to a page in the IT self service portal. One option would be to instead to replace the link there with this one (assuming students can actually sign up with their @tilburguniversity address) 
https://nl.mathworks.com/academia/tah-portal/tilburg-university-30348529.html

**Comment by andreantonacci** [comment]
Thanks, I've added both of them.

0b677c2
