### ISSUE TITLE
Missing `tilburg-update` branch referred to in Contribute instructions

### ISSUE THREAD

**Issue by mvuorre** [tilburgsciencehub/website#1300]
Hi, thinking of adding a few Makefile things but can't get the project up and running locally. Specifically, [here](https://tilburgsciencehub.com/topics/collaborate-share/project-management/engage-open-science/contribute-to-tilburg-science-hub/pullrequests/): 

2. Within your version of the forked repository, move to the `tilburg-update` branch and create a new branch for each significant change being made.

<https://github.com/tilburgsciencehub/website/blob/392395de289562cfaad4a83926110053113f82e2/content/topics/Collaborate-share/Project-management/contribute-to-tilburg-science-hub/pullrequests.md?plain=1#L54>

But there is no `tilburg-update` branch in source:

<img width="747" alt="image" src="https://github.com/user-attachments/assets/37d16bd2-d6f1-4ad5-972d-2f9e048f741a">

(Unless I am wrong which is very much a possibility :P) it'd be great if the instructions were updated. Should I base my work on the `main-flask` branch?

**Comment by mvuorre** [comment]
I see this is related to #1297 (contributing instructions seem outdated).

**Comment by krzysztof99xd** [comment]
Hey @mvuorre , 
Thank you for your interest in contributing to Tilburg Science Hub.
Yes, the contribution information is not fully updated yet (since we are moving to Flask and are still in the process of updating the content). Hopefully, it will be updated soon. Apologies for that. 

Yes, `main-flask` is the main branch to which pull requests should contribute.  Please find below the way you could contribute to the website.

1. Clone the repository using `git clone https://github.com/tilburgsciencehub/website.git`
2. Follow the installation guidelines that are in README.md file in this repository (either using Docker or running by flask command). 
3. Once you have a website running locally, create a new branch on which you develop your content. Please note that since the website fetches the content from the database, in order to see your changes on the website you need to rerun `python content_to_db.py` script. 
4. Once you are done with content creation, create a pull request with a short description of what changes you made. Someone will review it.

In case something is unclear, please do not hesitate to reach out to us again!

**Comment by krzysztof99xd** [comment]
Hey @mvuorre ,
We have updated our website, with the way how people can contribute to our website. 
Please let us know if something is unclear.
