### ISSUE TITLE
Development Call: automation scripts to install software

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#193]
# Development Call

## Getting started

Many users migrate to the cloud or use pre-installed systems (e.g., the Tilburg Blade) to run their software. Yet, cloud computers need to get reinstalled and the Blade resets every month (as we all know...).

So, what are best practices to install software from scratch? I think anaconda knows this with environments (right)? But how to install "other" stuff, e.g., stata packages? 

## Objectives

The goal of this building block is to (a) show best practices of automating software installation (e.g., environments in Anaconda, versus a simple shell script), (b) showcase example scripts that "do" the job. Importantly, these scripts need to be platform-independent (windows vs. linux vs. mac), to ensure that everybody can use them.

**Additional context**

Here's the code that @nazlialagoz currently uses to install stuff on the blade. Maybe it can be used as an inspiration to what our building block ultimately will have to achieve.

```

REPLICATION INSTRUCTIONS AND TIPS:
1. The scripts in this folder do descriptives, and do regression analytics

Configure AWS and get_externals.bat

2. Modify your environment variables
	A. Add STATA etc. to PATH (copy and paste below line in your environment variable called PATH)
	   C:\Program Files\Stata17;C:\Program Files\R\R-4.1.1\bin;C:\Python27;C:\Anaconda3\Scripts
	B. Add your R library to R_LIBS_USER to your environment with value of your own library. 
	   Find this path by .libPaths() query in R.
	   (e.g., E:/Users/u246547/Documents/R/win-library/4.1)
	    

3. Install packages:
	A. STATA
	set more off, permanently
	ssc install estout
	ssc install REGHDFE
	ssc install ppmlhdfe
	ssc install gtools
	ssc install coefplot
	ssc install mdesc
	ssc install ftools
	ssc install reghdfe
	ssc install unique
	ssc install xtqreg

	B. R
	- see below - 

4. Restart command line

5. Run the makefile. (write "make" -w/o quotations- in command line)

# **If you are encountering an error saying that you do not have a file that is needed for make
# run each line in get_externals.bat seperately through the command line. Most of the time this
# solves the problem or you learn what is preventing one of the files from being downloaded (e.g.,
# no space left on your PC).

R Packages:
install.packages(c("ggplot2",
		"devtools",
                 "did",
                 "data.table",
                 "dplyr",
                 "tidyverse",
                 "patchwork",
                 "lfe",
		"lubridate", 
		"finalfit", "coefplot", "tableone",
                 "fastDummies",
                 "ggthemes",
                 "bacondecomp",
                 "kableExtra",
                 "fixest",
                 "tidyr",
                 "statar",
                 "stringr",
                 "haven",
                 "envalysis",
                 "ggeffects",
                 "gridExtra",
                 "cowplot",
                 "AER",
                 "stargazer",
                 "starpolishr",
				 "CLVTools",
				 "forecast", "caret","e1071", "MASS","BTYDplus"), dependencies = T)
				
devtools::install_github("ChandlerLutz/starpolishr")
install.packages("stringi",type="win.binary")		
```

## Deliverables

**Describe the solution you'd like**

A building block that discusses what options exist for automating the installation, "after" the OS has been installed.

The building block should work on GUI systems (i.e., not running in a "blackbox" Docker image), to ensure users will actually be able to interactively use the system. It must work on Tilburg Blades, too.

- [ ] **A Building Block:**
  - Purpose: Automate the installation of software and packages
  - Motivation: See above...
  - Suggested title: *Ex. "How to automatically install software and packages in the cloud"
  - Suggested keywords: cloud, automation, software, install, setup
  - Suggested short link: install/cloud, install/blade

**Comment by hannesdatta** [comment]
@lachlandeer, would you be able to comment on this/modify this dev request? You have much more experience w/these kinds of things, so any pointers are welcome so that somebody at TSH can develop this. If you have scripts to share, let us know please.

**Comment by lachlandeer** [comment]
hi, so this might be easier to iterate on live ... but here's some thinking aloud.

Let's for the moment abstract completely away from STATA because it is a little unique in how it manages packages etc. i.e. let's think how we would get this to work within the R / Python / Julia universe, then back out a way to extend to STATA

1. Do we need to be blade / windows specific? Let's assume no in what follows so we think thru plans over 3 systems

Essentially we want a package (software) manager to do all the work for us so we don't have to manually do things... We can then write up a set of instructions as a shell script and run that.

For Windows, I guess we can try chocolatey - it seems to do what we want but I have no experience with it as I haven't run on Windows in years. Chocolatey *should* also add everything to PATH for us.

For Mac we use brew

For debian folks, apt will do it for us

Thus, a starting point could be a script for each that goes thru an installs the software we need once one downloads the appropriate script from the internet (i.e. we dump a bunch of install scripts somewhere that can be wget-ed). I would think about having a script something like 'configure_blade_python.bat' or etc

2. You also mention the installing of extra packages for STATA, R etc

These are project specific, so one would imagine they are project specific solutions that are canned into one's project {Sn,m}akefile. Here's how I would encourage one to think:

* If python -- use a virtual env package, have a requirements.txt in your main repo and have a rule that installs from this list
* If R - do similar, but i would encourage `renv` or `pak` as the package management tool.

i.e. this kinda stuff:

```
# **If you are encountering an error saying that you do not have a file that is needed for make
# run each line in get_externals.bat seperately through the command line. Most of the time this
# solves the problem or you learn what is preventing one of the files from being downloaded (e.g.,
# no space left on your PC).

R Packages:
install.packages(c("ggplot2",
		"devtools",
                 "did",
                 "data.table",
                 "dplyr",
                 "tidyverse",
                 "patchwork",
                 "lfe",
		"lubridate", 
		"finalfit", "coefplot", "tableone",
                 "fastDummies",
                 "ggthemes",
                 "bacondecomp",
                 "kableExtra",
                 "fixest",
                 "tidyr",
                 "statar",
                 "stringr",
                 "haven",
                 "envalysis",
                 "ggeffects",
                 "gridExtra",
                 "cowplot",
                 "AER",
                 "stargazer",
                 "starpolishr",
				 "CLVTools",
				 "forecast", "caret","e1071", "MASS","BTYDplus"), dependencies = T)
				
devtools::install_github("ChandlerLutz/starpolishr")
install.packages("stringi",type="win.binary")		
```

should be replaced with a something like a rule that runs Rscript -e 'renv::restore()' or 'pip install -r requirements.txt'

I'm going to defer a STATA discussion for a later point in time....

As a side note: why is docker too black-box-ish? one can run a docker container iteratively

**Comment by lachlandeer** [comment]
I'm going to close this since we have docker stuff and some `packrat` things for R. 

#631, #632 #633 for some recent calls to develop new stuff for Python and R
