### ISSUE TITLE
create data source building block

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#320]
1) Need a building block on data source used in marketing & econ (1 block)
2) Structure

Overview:
Why public data is cool to use

Collection of links w/ a small description
- probably want to use a table to do this

Use the TSH style guide to see how to make a table

**Comment by hannesdatta** [comment]
- Make it "minimal" -- have the structure, but let us just have a small list of resources to start w/ and then close this issue

**Comment by BilgeKasapoglu** [comment]
Dear @hannesdatta,

I created a building block for the data sources. It is a very brief one. If I manage to find good datasets as these ones, I will improve the building block over time. Please let me know if you think something is wrong or should be improved in the building block. Since this is my first time creating content for the website, I hope I did not do something wrong. Thank you

All the best,
Bilge

**Comment by casruger** [comment]
Since this has been online for 5 months now and Bilge left the team I close this issue
