### ISSUE TITLE
[Q]: feature TSH op instagram

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#335]
### Contact Details

h.datta@tilburguniversity.edu

### Shoot!

Mailed Annemeike about it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hannesdatta** [comment]
Please make a list w/ potential instagram posts and links to our page
(5 links) + explanation for WHICH students this is useful

**Comment by casruger** [comment]
- Every student (especially master and PhD students)

Every university student is expected to be able to write a well-structured paper. This is especially the case for students writing their thesis. At Tilburg Science Hub we have an overview of which sections a well structured empirical paper (or a master thesis, or a chapter of a Ph.D. thesis) should contain and in which order. 
https://tilburgsciencehub.com/tutorials/more-tutorials/write-an-academic-paper/write-an-academic-paper/

- Every student (especially master and PhD students)

On our site, we also explain LaTeX, a professional typesetting system widely used in academia because it can produce complex documents like journal articles, books, technical reports. We explain how you can set up LaTeX, help people understand how they can effectively use it, and we provide a thesis template to help students get started. 
https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/write-your-paper/latex-templates/
https://tilburgsciencehub.com/tutorials/more-tutorials/write-your-first-latex-document/your-first-article/

- For students using Python, R studio, Stata or MATLAB

TSH offers full setup tutorials for all these different programming languages. In addition, the platform offers information on how to get started with the language by for example explaining how to import packages. https://tilburgsciencehub.com/building-blocks/configure-your-computer/statistics-and-computation/

- Quantitative studies (marketing analytics, data science, econometrics

We offer a broad range of interesting information from collecting data by for example web scraping till running regression analysis (including data cleaning and interpreting results). Offering this information via a public website can help the students during but also after their studies find the accesable information they are looking for. 
https://tilburgsciencehub.com/building-blocks/collect-data/webscraping-apis/scrape-static-websites/
https://tilburgsciencehub.com/building-blocks/analyze-data/regressions/regression-analysis/

- For non research students 

We also offer practical tips such as how to prepare for Scrum meetings. Scrum is one of the most popular agile frameworks very often used in all kinds of different companies ranging from tech firms like Google to Law firms like Avvo. Learning how to work and getting used to this way of working improves both efficiency during school projects as well as repair for the working field. 
https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/project_management/meeting_preparation/

**Comment by casruger** [comment]
A reminder mail has been sent

**Comment by casruger** [comment]
Hannes has received the oppertunity to talk to Femke Trommels from the newsroom of Tilburg University. Therefore, I have assignt him to this project.

**Comment by hannesdatta** [comment]
This has been picked up by our new social media team member and doesn't need an issue anymore.
