### ISSUE TITLE
move next page button up

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#347]

**Comment by hannesdatta** [comment]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/16557730/163382993-812fbe34-ee15-4f9f-94e2-fb56c1508fc2.png">

**Comment by hannesdatta** [comment]
Please define how it should look like, be making your own mock-up.

**Comment by casruger** [comment]
I completely misunderstood the next button on the building block pages. I thought they had the same purpose as on the tutorial pages, namely continuing to read on the same topic, however, at the building blocks they move you to the next building block which in most cases has another topic. 

At the tutorial pages the current place is best, however I would name it 'continue reading'. 

At the building block pages I would remove the next button since we also have the related post element and can add 'see also' element which are in my opinion more useful than the next page. And now you create some confusion with all of the possible elements see picture: 


![Image](https://user-images.githubusercontent.com/51459017/166142903-61c0d0b2-19ac-4159-96a7-6a9b9b6a03eb.png)



A couple examples: 


![Image](https://user-images.githubusercontent.com/51459017/166142458-7bd75515-8215-4f4e-95b5-e0435569c305.png)


![Image](https://user-images.githubusercontent.com/51459017/166142492-d6aeb645-36af-4d5f-8176-fb7ea500ecaf.png)



![Image](https://user-images.githubusercontent.com/51459017/166142846-de8327db-57b1-4098-bb2b-02918d15ea02.png)

**Comment by hannesdatta** [comment]
Implemented - as a final action, please add to our style guide that building blocks should only be 1 page long. Tutorials can be multiple pages. @casruger
