### ISSUE TITLE
run a simple A/B test on the site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#365]

**Comment by casruger** [comment]
Created pull request #386

**Comment by casruger** [comment]
Running two tests
Firstly, 50% of the homepage visitors will see the original homepage, the other 50% will see the homepage with fewer text in the three blocks and with more call to action written texts: 
![image](https://user-images.githubusercontent.com/51459017/167120273-ff8393c1-868b-4319-96e5-e3018328aea4.png)

Secondly, 50% of the README best practices page (https://tilburgsciencehub.com/building-blocks/store-and-document-your-data/document-data/readme-best-practices/) see only 3 related posts instead of the original 5. 
![image](https://user-images.githubusercontent.com/51459017/167120491-24b31b08-7e24-4ce4-a840-20a09af3349c.png)


Depending on the results these changes could be made to the website for all visitors.

**Comment by hannesdatta** [comment]
Any results - you turned this on a couple of days ago already right?

**Comment by casruger** [comment]
Since the behavior flow of the visitors is better in the fewer text variance we implement this one permanently. 

Dropout rate on the home page with all the links was 63.1 (this is the percentage of people seeing the homepage and then leaving)
The dropout rate of the home page with the fewer text was 52.6. 
In addition, the tutorials and building blocks page were visited more on the fewer text variant showing that more people see the content we offer in that version. 


The number of related posts did not have any remarkable effects, therefore this test was stopped and no changes were made.

 New issue for making the homepage version with fewer text permanent #393
