### ISSUE TITLE
Imrpove seo

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#510]
Perform SEO checks (e.g., using SEO spy suit) on our website, and define follow-up actions. Discuss these follow-up actions and their prioritization w/ Hannes, so we can decide which ones enter production.

**Comment by casruger** [comment]
Continue to improve our seo by working on the docs: https://docs.google.com/document/d/1xn2WrfSM5kGgGkQ44Uj-3Elt2g4UsYUL/edit?usp=sharing&ouid=117986693098938196251&rtpof=true&sd=true

**Comment by casruger** [comment]
**Deliverable:** 
Before and after of increase in seo score.

**Comment by thierrylahaije** [comment]
All pages that were in the list that Cas and I made have been adjusted. Only the header and footer still need to be edited. Main issue there is that the icons / images do not have alt attributes assigned to them. I will check the files and update them.

**Comment by casruger** [comment]
I have updated the alts of the header and front page last month and published them in this pull request: https://github.com/tilburgsciencehub/website/pull/587. 
And published the changes to the footer in this pull request https://github.com/tilburgsciencehub/website/pull/591.

@thierrylahaije I think the changes to the pages have only been made on your repository, since I have not seen a pull request for the remaining pages, and these + the changes of your first pull request have not been published (Lanchlan wants an explenation before we publish them).

**Comment by lachlandeer** [comment]
#580 includes the last of these that I can see 

Closing this
