### ISSUE TITLE
Update build packages on Netlify

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#517]
We use Netlify to deploy all of our sites. 

### What happened?

Sites will stop building in November - we need to update the Netlify build images for all sites.

![image](https://user-images.githubusercontent.com/16557730/190643839-6de8f469-8b89-479c-ae7e-f6829954eae1.png)

See here for the instructions:

https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

__DELIVERABLES__
- test all build images 
- deploy new build images

**Comment by juliehabets** [comment]
@thierrylahaije do you have an update on this?

**Comment by thierrylahaije** [comment]
@hannesdatta I see I have been assigned to this issue right after I started working here, but this is not one of my expertises, since I have no experience with Netlify. Do you want me to do research on this and fix it myself or is it smarter to pass this on to @casruger ? Maybe he can fix this issue quicker than I can.
