### ISSUE TITLE
[Q]: Summary of user interactions with site

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#529]
### Contact Details

lachlan.deer@gmail.com

### Shoot!

To get a handle on a potential cleaner way to present the volume of material we have on here, we need a better understanding of how people interact with the site ... 

Which pages are viewed most? 
How do users progress through the site in a visit? 
For returning users, what do they come back looking for? 

It would be great to build up a report of this (maybe its already available via google analytics) that we can peruse

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by casruger** [comment]
@lachlandeer I made a quick overview of the requested content to give you an idea of what you can find in Google Analytics. 

https://docs.google.com/presentation/d/1D4d4Lo0MuHEnTpNYdcuC8zVM_7ezpj0F/edit?usp=sharing&ouid=117986693098938196251&rtpof=true&sd=true

It is hard to make one dashboard for this since it is relatively specific information you will need from different types of (in analytics) sources. I would gladly explain where you can find the most interesting information or if you have any specific information you are looking for let me know and I will search for it.
