### ISSUE TITLE
[Feature]: New Content Page Ideas for TSH

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#578]
### Is your feature request related to a problem? Please describe.

We want new content, here's a spot where we can put some ideas.

### Describe the solution you'd like

Respond to this Issue with what you want added. Use the following (short) format

Title (What you want a few words, or name of package)

One sentence explaning why you think this is a valuable addition.

**Comment by srosh2000** [comment]
Title: Pipeline from scikitlearn - automate your machine learning workflow

Why: 
Scikit-learn's pipeline class is a useful tool for encapsulating multiple different transformers alongside an estimator into one object, so that you only have to call your important methods once (fit(), predict(), etc). It helps to enforce desired order of application steps, creating a convenient work-flow, which makes sure of the reproducibility of the work.

Resources for more info:
- https://towardsdatascience.com/a-simple-example-of-pipeline-in-machine-learning-with-scikit-learn-e726ffbb6976
- https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html

**Comment by casruger** [comment]
Title: Use k-fold cross-validation to prevent overfitting

Overfitting is well-known issue of many predicting models which makes the model have issues with generalization. The concept fits well at our lack of 'analyse the data' building blocks. We can explain how to detect overfitting and how we can change the parameters to prevent it.

**Comment by casruger** [comment]
We have two pages in which we refer to our 'competitors'. I think we would benefit by keeping the pages with their title, but writing our own content here. 

Manipulate Data: https://tilburgsciencehub.com/building-blocks/prepare-your-data-for-analysis/data-preparation/manipulate-data/
In-depth Introduction to Machine Learning and R: https://tilburgsciencehub.com/building-blocks/analyze-data/machine-learning/introduction-to-machine-learning/

**Comment by casruger** [comment]
Title: Model assumption Homoscedasticity. 

We currently have a page explaining the visual check for linear models, however this is not very in-depth and does not explain significant tests you can do (like Bartlett's test). Making a separate building block for each assumption allows more in-depth why the assumption must be met, and how you can test these assumptions with an alpha of 0.05 rather than personal visual interpretation.

**Comment by DiSanchz** [comment]
Title (proposed): Use Dockerhub to share your projects.

Why: This building block would be a logical complement to the one on importing environments with docker and google cloud. After having described in the aforementioned building block how to import an environment in Gcloud from an existing dockerfile, a new building block explaining the user how to read/design these dockerfiles and make them available to collaborators or users aiming to replicate their porjects would complete the cycle of collaborating on projects through docker. Both sides of the process would be covered, export and import.
