### ISSUE TITLE
[Q]: Organizing a hackathon for students

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#638]
### Contact Details

h.datta@tilburguniversity.edu

### Shoot!

Last year, a few students and I came up with the idea to organize an __open science hackathon__ for students.

__What's in it for students?__
- Learning how to contribute to open science projects
- Applying their skills in real-life
- Creating code snippets and tutorials that will be made publicly available at Tilburg Science Hub
- Working together with students from other disciplines (and thereby learning from other fields)

__What's in it for us?__
- Boosting awareness for the Tilburg community
- Creating new content

__Potential agenda of such a hackathon__:

- 30-minute presentation on how to contribute to open science projects
- Brainstorm w/ faculty about building blocks to put online (maybe in groups)
- Pizza for everyone
- Students start coding
- TSH RAs need to be present to help students make their contributions
- Drinks

__Deliverable:__

Please work out a plan to organize such a hackathon. A few thoughts:

- When in a semester (depending on exams, other events, etc.) -- ideally before the summer!
- How to target/inform students?
- How many students would we expect?
- How to practically organize (e.g., at what time to organize the hackathon, which rooms are nice)

You're free to use ChatGPT for inspiration, etc.!

Ideally, this really takes place before the summer.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fleurlemire** [comment]
Hi Hannes, i adjusted my onboarding task and came up with a first draft proposal. 
https://docs.google.com/document/d/1jcLpUXOzbptqEPstrmJaqrcSk2ktM_cr/edit

**Comment by hannesdatta** [comment]
Thanks!Here's my feedback

**Comment by hannesdatta** [comment]
@fleurlemire - can you report on any update here (according to the comments added above)? As a location suggestion, could you please look into Mindlabs at Tilburg Central Station (it's part of the university). Thanks.

**Comment by fleurlemire** [comment]
@hannesdatta, Sorry this took a little longer. I've been sick the past few days, so I'm only really getting around to this now.
I have adjusted the proposal including program. What do you think about it? I also added a few comments. https://docs.google.com/document/d/1jcLpUXOzbptqEPstrmJaqrcSk2ktM_cr/edit

Mind labs sounds like a good location for this. This indeed gives a more cool feel and less formal feel to the event.
I'm going to see if this is possible and what other possibilities for locations there are.
I will also contact colleagues and the faculty for availability. Does this concern both RAs and, for example, you, Tobi, etc?

**Comment by fleurlemire** [comment]
@hannesdatta I have reached out for information regarding the location. I tried to find the right contact person/adress, but:

- Mindlabs itself; i send a message with questions but no response yet, maybe this takes longer because of holiday
- planning-TiSEM@uvt.nl; said they never heard of us, but that i needed to ask Conference & Event support
- cesupport@tilburguniversity.edu; conference and event support, no response yet, but got an email that responses can take longer because of holiday period

Should I wait 2/3 weeks till after holiday is i get responses back, or should I send it to something else? I wasn't sure but this came up when looking for it

**Comment by fleurlemire** [comment]
Hi @hannesdatta,

I got the following message back from MindLab;
_Beste Fleur,
Dankjewel voor je belangstelling voor MindLabs! Altijd welkom in ons mooie gebouw.
De hackathon zou je kunnen organiseren in een van onze collegezalen. We hebben drie collegezalen, elk met een capaciteit van ongeveer 60 personen. Twee van de drie zalen kunnen gecombineerd worden tot een zaal met een capaciteit van 120 personen. Mocht je het gebouw nog niet kennen, dan wil ik je voorstellen om een keer langs te komen zodat we de opties kunnen doornemen._

So I definitely think it's possible to make it happen here. Before I look further into the possibilities, I think it is important to research the availability of the team, to be able to pinpoint a specific date and then look at the location for this date. Whose availability is important now for this event? Is this mainly about you, Tobi, Lachlan etc, or also the RAs? Since it is also ahead of time, I also don't know if everyone already knows if he or she is available, does this matter a lot?

**Comment by fleurlemire** [comment]
@hannesdatta I have send you an email about this issue. The subject is: _openen instagram_

**Comment by hannesdatta** [comment]
Never took off. Let's retire.
