### ISSUE TITLE
[Improvement]: Reduce GitHub footprint of TSH

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#645]
### Contact Details

h.datta@tilburguniversity.edu

### What happened?

When cloning our site, I noticed we have a HUGE footprint on GitHub --- our site is 55MB (and this used to be much less).

__Deliverable:__
- List of the top 100 biggest files in our repository (in descending order of file size), including files in our history -- it could be we wrongly committed files
- Recommendation (NOT actually doing it yet) as to which files can be completely wiped from our history to reduce the footprint
- [Optional, upon @lachlandeer decision; it's not critical]: A building block: how to reduce the size of your GitHub repository when it became to large (kind of sharing the experiences from working on this).

### To reproduce

- use terminal/git bash and type this command to see the file size:

```
echo https://github.com/tilburgsciencehub/website.git | perl -ne 'print $1 if m!([^/]+/[^/]+?)(?:\.git)?$!' | xargs -I{} curl -s -k https://api.github.com/repos/'{}' | grep size
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Agreed its too heavy

My guess is that its a combo of two things:

- Excess branches -- many of which are stale -- I plan to go pruning soon
- All the png files etc that are loaded into the building blocks.  - not sure what we can do there if its the cause


Let me try and fix the excess branches issues and see if that trims down size. Then we can go hunting for more space saving

**Comment by lachlandeer** [comment]
OK I've been investigating this a little 

1. **Movie Files** 
There's approx 30 MB of movie files:

```bash
find -type f -name "*.mov" -print0 | du -csh --block-size=1M  --files0-from=- --total-s
```

returns the following: 

```
5	./content/building-blocks/configure-your-computer/infrastructure-choice/img/copy-paste-key.mov
7	./content/building-blocks/configure-your-computer/infrastructure-choice/img/ssh-keygen.mov
5	./content/building-blocks/configure-your-computer/infrastructure-choice/img/git clone.mov
5	./content/building-blocks/configure-your-computer/infrastructure-choice/img/nano.mov
9	./content/building-blocks/configure-your-computer/infrastructure-choice/img/config-key-on-git.mov
30	total

```

Potential Solution: Host them elsewhere (eg. YouTube? GoogleDrive) and embed them into the site rather than keep them in the GH repo

2. **All Large Files** 

What else is large going on in here?

```bash
find . -type f -exec du -ah --block-size=1M {} + | sort -nr | head -n 20
```

returns the following: 

```
81	./.git/objects/pack/pack-e6e881feab3e117d488f609169353ed025a13c4b.pack
43	./public/building-blocks/develop-your-coding-skills/learn-to-code/data-wrangling/data_wrangling_R-dplyr.html
43	./content/building-blocks/develop-your-research-skills/learn-to-code/data-wrangling/data_wrangling_R-dplyr.html
9	./content/building-blocks/configure-your-computer/infrastructure-choice/img/config-key-on-git.mov
7	./content/building-blocks/configure-your-computer/infrastructure-choice/img/ssh-keygen.mov
5	./content/building-blocks/configure-your-computer/infrastructure-choice/img/nano.mov
5	./content/building-blocks/configure-your-computer/infrastructure-choice/img/git clone.mov
5	./content/building-blocks/configure-your-computer/infrastructure-choice/img/copy-paste-key.mov
5	./content/building-blocks/collaborate-and-share-your-work/write-your-paper/lyx-slides-template.zip
5	./content/building-blocks/collaborate-and-share-your-work/write-your-paper/lyx-research-paper-template.zip
3	./content/tutorials/scale-up/running-computations-remotely/img/launch-instance.gif
3	./content/tutorials/scale-up/running-computations-remotely/img/connect-windows-instance.gif
3	./content/tutorials/more-tutorials/airbnb-workflow/images/download_data.gif
3	./content/tutorials/more-tutorials/airbnb-workflow/images/airbnb_expansion.gif
3	./content/building-blocks/automate-and-execute-your-work/reproducible-work/img/open-portal1.gif

```

So in addition, 

* there's some massive git object that needs to be removed
* A slide deck that appears twice - this should get hosted on a different repo and then we link to it rather than what we have
* Lyx templates that again can be hosted elsewhere and linked to 
* gifs I guess we can host those elsewhere too

**A Solution?**

We should create some space online where large files can be uploaded and referenced/loaded onto the site, rather than keeping them in the git repo. Once we have that running we can move the files that cause most of the issues. 

The large git object is tricker to handle as simply deleting it is not a good idea, see [here](https://stackoverflow.com/questions/11050265/remove-large-pack-file-created-by-git)

**Comment by hannesdatta** [comment]
Will be solved when moved to Flask. Let's retire.
