### ISSUE TITLE
onboard new RAs

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#647]
- add new students to the meetings on Teams
- pair them up? @shrabasteebanerjee 
- update the onboarding tasks @lachlandeer at https://github.com/tilburgsciencehub/onboarding/wiki/Checklist-to-onboard-new-team-members
- set the date of the first meeting @lachlandeer 
- fix dates of drinks -- 13 April '23

**Comment by lachlandeer** [comment]
I think we should add a page somewhere in the onboarding guide for us as a core team with a checklist of things we need to do when we bring on new people.. something like:

- [ ] Organize contracts with Scarlett
- [ ] Add new members to Teams
- [ ] Add new members to weekly WoW meeting calendar
- [ ] Add new members to GitHub Organization 
- [ ] Add new members to clockify
- [ ] Set-up Onboarding session + email to organize (perhaps with a draft email ready to go)
- [ ] Match new and existing members together in a buddy system, email matched pairs 
- [ ] Host Onboarding Session 
- [ ] Organize a welcome drinks event 

Why? Because my head is too full of other stuff to remember all of this & i still probably forgot some things. Thoughhts @shrabasteebanerjee

**Comment by shrabasteebanerjee** [comment]
I like this! for this edition, i've checked off the stuff we've done so far -- will you send out the onboarding email @lachlandeer ? i can then send the buddy emails! and yes, for the future, this can be a page in the core team onboarding todos.

**Comment by lachlandeer** [comment]
Awesome -- thanks @shrabasteebanerjee for checking off what we've done so far

I'll send the onboarding email today. I'll CC everyone ...
