### ISSUE TITLE
[Feature]: New Header For site

### ISSUE THREAD

**Issue by lachlandeer** [tilburgsciencehub/website#652]
### Contact Details

lachlan.deer@gmail.com

### Is your feature request related to a problem? Please describe.

I'm always frustrated when i get to the site and have to navigate thru the header bar to find what I want ...

I've thought about this a lot (too much) & wonder whether a redesign as follows is better

### Describe the solution you'd like

rather than "tutorials", "building blocks", and "examples"   as the main headers if we had themes of content as the main header, for example 

"Configure", "Data Collection & Management", "Analysis", "Cloud" and "Collaboration Tools"

and then under each we could have building blocks, examples and tutorials

Why i think this might work ... When i get to the site I know what I want to do "I want to store my data on AWS but dont know how" (where I sit under the categorization I propose), I don't approach the site and think "do i want a building block or a tutorial today"

This would clearly be a lot of work... and I might think about A/B testing it even. But I think it might enhance usability a lot. What does everyone think @shrabasteebanerjee @hannesdatta @kleintob 

Probably needs a much longer discussion!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lachlandeer** [comment]
Relates to #281 - learning paths

a header could be (in order)

* Tour 
* Learning Paths (once we have them)
* Each of "Configure", "Data Collection & Management", "Analysis", "Cloud" and "Collaboration Tools"
* About

Or we could put the learning paths from the home page under the take the tour button, instead of start with a tutorial, "View our learning paths"

This also gets us away from the tutorials as someone's first touchpoint -- as they do assume quite a bit of knowledge i would imagine very new to the site viewers being put off by this as a first experience

**Comment by kleintob** [comment]
I think this is a very good and valid point. I would be in favor of moving more to a task-based UX approach, instead of the more administrative one we have.

Two things that come to mind in addition, triggered by what you write:

  1.  We may want to guide people more to the search bar. In the end of the day, this is the most efficient way to access content when they know what they want, and it works quite well.
  2.  If we move to a more task-based approach, we may want to put stuff front and center that is also in the end of the day the key to getting a paper published (or to writing a good thesis etc): a good analysis. My thinking is that there are too many papers that are well-done (all the code is great, make file, etc.) but ask the wrong question or don’t have a credible empirical approach. This also relates to our aim to develop the causal inference content: if we can show to people what state of the art and best practice is for robustness checks etc and how to do them, then we could really create some value to users. It would be amazing if we could become the place where people come first when they think about this stuff. (think: at what level to cluster standard errors, how to test this, whether one needs one of the new two-way fixed effects estimators instead of the classical Diff-in-diff one, some tests for weak instruments, some RDD nonparametric testing, etc.)

t



From: Lachlan Deer ***@***.***>
Reply to: tilburgsciencehub/website ***@***.***>
Date: Wednesday, 15 March 2023 at 03:27
To: tilburgsciencehub/website ***@***.***>
Cc: Tobias Klein ***@***.***>, Mention ***@***.***>
Subject: [tilburgsciencehub/website] [Feature]: New Header For site (Issue #652)

Contact Details

***@***.******@***.***>

Is your feature request related to a problem? Please describe.

I'm always frustrated when i get to the site and have to navigate thru the header bar to find what I want ...

I've thought about this a lot (too much) & wonder whether a redesign as follows is better

Describe the solution you'd like

rather than "tutorials", "building blocks", and "examples" as the main headers if we had themes of content as the main header, for example

"Configure", "Data Collection & Management", "Analysis", "Cloud" and "Collaboration Tools"

and then under each we could have building blocks, examples and tutorials

Why i think this might work ... When i get to the site I know what I want to do "I want to store my data on AWS but dont know how" (where I sit under the categorization I propose), I don't approach the site and think "do i want a building block or a tutorial today"

This would clearly be a lot of work... and I might think about A/B testing it even. But I think it might enhance usability a lot. What does everyone think @shrabasteebanerjee<https://github.com/shrabasteebanerjee> @hannesdatta<https://github.com/hannesdatta> @kleintob<https://github.com/kleintob>

Probably needs a much longer discussion!

Describe alternatives you've considered

No response

Additional context

No response

Code of Conduct

  *   I agree to follow this project's Code of Conduct

**Comment by shrabasteebanerjee** [comment]
I agree with both points! It is certainly difficult to find specific pieces
of content through the building block/tutorial route, and having more stuff
on the analysis side (+ highlighting it) would be great. Is the first part
something for our developer to work on, once we have flagged which posts go
under  "Configure", "Data Collection & Management", "Analysis", "Cloud" and
"Collaboration Tools"?

**Comment by hannesdatta** [comment]
How do you like the search bar on https://mermaid.js.org/?

It's prompting users to remember a shortcut for it (see screenshot), and when you click on it, it gets a very nice focus. Easy to implement.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/16557730/225295911-777dcaeb-118e-49df-8827-7b7b29f4cb12.png">

**Comment by lachlandeer** [comment]
@hannesdatta very cool for those who know what they want! Does it also come with a different backend doing the searching?
