### ISSUE TITLE
Reactive our social media channels

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#662]
__Background:__

TSH is active on Twitter and LinkedIn. But we last posted Dec '22.

__Deliverable:__
- A document with curated posts on these channels. 
- We ideally review them, and then you can start posting.
- We strive to be active weekly - if you want to be more active, feel free!
- Please also start using Twitter yourself - e.g., by liking others' posts that you feel make sense, by following other open science people. Start __owning__ our Twitter channel.

You can get inspired by @fleurlemire's onboarding task - this was already good content.

**Comment by hannesdatta** [comment]
@fleurlemire  -  please post your draft doc here.

My feedback:
- When posting externally, we need a "different" layout that underscores (a) it's not our content, and (b) we "humbly" want to highlight it to our users because we think they may find it interest.
- Go for posting internal TSH posts
- Please actively tag, activate people. ALWAYS find ambassadors that can retweet. --> SEND OUT message to our team to co-promote.

**Comment by fleurlemire** [comment]
Hereby I post First draft of posts here which is reviewed already.
[First posts Linkedin & Twitter .docx](https://github.com/tilburgsciencehub/website/files/11170528/First.posts.Linkedin.Twitter.docx)

- External posts are going to be changed with a different layout
- Green text is already posted on the social media channels

**Comment by fleurlemire** [comment]
@hannesdatta I changed the layout of external posts and i do now have 4 drafts for this. Can you please review it and give your opinion? After approval I will change the other external posts to the final format. 

[proposal external posts.docx](https://github.com/tilburgsciencehub/website/files/11170552/proposal.external.posts.docx)

**Comment by hannesdatta** [comment]
Great work!

- great color scheme
- the discovery aspect needs to become even more prominent
- get some inspiration from how other people acknowledge work by others on social media; we're not 100% there yet. do check my comments in the doc.
- wouldn't mention a name (like LD in the ad now); it seems it's on-site content (while its external content).

**Comment by fleurlemire** [comment]
@hannesdatta 
for the external posts, I changed the layout a little. I still have some questions left but i want to ask you to review the places of text already and help me out with my questions so i can change that after. 
You can find my changes here below: https://docs.google.com/document/d/1jTHe3odA13qbfS0FtGZk6bGkeYSA-RD7/edit
and i have the following questions about it:

- is the tilburg science hub discoveries prominent enough now?
- Is this what you mean with topic less prominent (smaller for example) or do you mean graph of tidyverse?
- I still do not exactly get your feedback about the text.  can you explain this maybe, then i will change this too. Yes, i will do that! Can you maybe explain this last part a little bit more? I get that we need to make it super clear that it is content from outside but it is not really clear to me what you mean the/expect from the as part of.. Can you maybe explain what you mean with this? first, do you mean in like the picture or text of the post itself ? and then i dont know what you mean with as part of what? like for example our mission or more like the researcher where the content is from? no right since we don't want name them in the graphs. I think this is not what you mean, but i tried something for the layout

Moreover, i added some internal post, where i want to ask you to review them. You can find them highlighted yellow on https://docs.google.com/document/d/1X4DYhO2IbLm5xPgP-oNwKEZV6q2dRySb/edit

**Comment by fleurlemire** [comment]
Hi @hannesdatta, I added some internal posts (new ones marked with yellow).
https://docs.google.com/document/d/1X4DYhO2IbLm5xPgP-oNwKEZV6q2dRySb/edit
Can you maybe please review them and give me your feedback, so I can start post them? 

- One question: What do you think about meet the team posts? Since Lachlan was not a fan of this idea of separate posts and wanted one post of everyone together. If I get your feedback on this, i will continue working on this.

**Comment by hannesdatta** [comment]
Good work! 

(1) I'm all in for the meet the teams post. Maybe judge yourself when is a good moment to post it -- i.e., there needs to be a good mix about content & a few of these team posts inbetween. Judgement is yours!

(2) I have also reviewed the two yellow-marked draft posts. I noticed that the audience was a bit 'off': recall our target groups:

> Who is Tilburg Science Hub for?
> 
> Are you a research master or PhD student? Use Tilburg Science Hub to quickly become operational and learn not only about how to properly code a specific algorithm but also how to address specific marketing-related problems.
> 
> Academic scholars, in turn, will be able to (1) reproduce published work in a more efficient way and (2) identify code snippets that might be useful, and (3) potentially become [contributors](https://tilburgsciencehub.com/contributors) at little cost.
> 
> Companies and data science enthusiasts can get efficient training into state-of-the-art tooling, and access to code to their own situation.

It's important we speak to _them_, not everyone on LinkedIn or Twitter.

Please incorporate these suggestions next time. And, did you know this style guide? --> https://tilburgsciencehub.com/contribute/style-guidelines/?utm_campaign=referral-short. You can try some prompts with ChatGPT for coaching you to apply these guidelines. Thanks!

**Comment by hannesdatta** [comment]
Hi Fleur,

I added my comments! Thanks! Really nice discoveries!!!

**Comment by fleurlemire** [comment]
Hi @hannesdatta,

I added some new posts and worked on your feedback, both are marked in yellow. Do you want to take a look at this and provide me with feedback: https://docs.google.com/document/d/1X4DYhO2IbLm5xPgP-oNwKEZV6q2dRySb/edit

Moreover, i created some kind of content calender in which we can see what is posted when, what will be posted when, and how many likes, retweets, views etc we've got per post together with that. I also uploaded this on the drive: https://docs.google.com/spreadsheets/d/131YwFOlN9qjdgR6SZP1vI96J2rZFbriG/edit?usp=drive_web&ouid=116027986602847265946&rtpof=true

I am looking forward to your feedback!

**Comment by fleurlemire** [comment]
Hi Hannes,

I worked on your feedback and changed some things. Do you want to look at it and let me know what you think?
https://docs.google.com/document/d/1X4DYhO2IbLm5xPgP-oNwKEZV6q2dRySb/edit

I have 2 questions:
- do you also want the courier for package names in the graphs (as i added now)?
- what about courier on twitter and linkedin. courier is not working on linkedin and twitter right? everything is placed in their fonts. I can make it bold itcalic etc on linkedin but i dont think i can change the font. Same for twitter. What do you think about this and want me to do with it?

**Comment by hannesdatta** [comment]
I have reviewed the doc - thanks!

- no courier in the graphics (it didn't look visually appealing there)
- i can't decide on (2) - my goal is that the article becomes better. if you think italics will do the job, then do it in italic.

**Comment by fleurlemire** [comment]
Hi Hannes, i added some more posts, both internal and external, marked in yellow.

**Comment by hannesdatta** [comment]
Hi Fleur,
I finally managed to comment on all of the posts.

In general, the tone is becoming a bit too canned. In the future, please try out a different writing style - or at least, try to make it sounds a little more natural (and less Chat GPT-ish) - using terms like "distinguished" (prof.), "valuable resource" etc., sounds a bit too much at times.

For the rest - REALLY exciting new stuff that you've discovered. Thanks!

**Comment by fleurlemire** [comment]
Hi Hannes,

What do you think about the external posts? We tried one before and I added the results in here: 

![Schermafbeelding 2023-08-17 om 14 32 09](https://github.com/tilburgsciencehub/website/assets/122876103/72ef4eee-5721-4ab6-8fde-f836ed27f791)

I also want to share with you the results of others post, so that the results can be compared: https://docs.google.com/spreadsheets/d/131YwFOlN9qjdgR6SZP1vI96J2rZFbriG/edit#gid=2018149474

What do you think about the results? Should we continue with this or is it not worth it in your opinion and should we focus on our own content?

**Comment by hannesdatta** [comment]
Thanks so much for prepping these stats!

While the ROI on external posts doesn't seem high, it is an invaluable contribution to learning about others and reaching out. See - I discovered NEW STUFF, simply because you broadcasted it via our channels. So, let us continue with it. It will help you stay innovative. Maybe we can think about featuring not only individual researchers, but let's say, five posts about activiteis from turing way, five posts from another open science group. that's actually a good idea: focusing on other larger initiatives/organizations and telling others about it. Can you think this through? Goals: individuals, but also organizations doing open science. 

In addition, could you please check out our new landing page at https://tilburgsciencehub.com and think about ways in adding MORE cards that feature additional/new content. e.g., can you think of a box that features most recent twitter or linkedin posts? some users stats? etc.? Pretend you have a super programmer available that can implement anything you want. What would that be? (oh, btw, the super programmer would be @thierrylahaije) ;). I WANT TO MAXIMIZE retention. People coming back to our site because they feel (a) there are cool people around, (b) it's usable content, (c) it's content that other people want.

We should definitely continue with introducing our team - this adds all our RA's friends to our network ;).

I'm happy with your initiative to refine/rethink: can you come up with additional suggestions on modifying our content strategy? 

Last but not least: please realize how amazingly you've grown our site. We're at 12k this month. Unbelievable (we were at like 4 or 5k in feb '23!). 

Oh, and finally: we're super depending on google (94% of our traffic is organic search). Maybe find ways to get previous users back to our site. Maybe google analytics helps you find some sweet spots.

Define separate issues for the things you want to follow up with, please :).

Thanks!

**Comment by fleurlemire** [comment]
I made separate issues for the landing page and google, since i think those are not really (completely) related to this. Moreover, I also want to follow op the external organizations posts and additional suggestions on modifying our content strategy, but since I think that is relate to this issue, I don't think it is needed to create more issues and I will add it in the content doc or a new doc.

**Comment by fleurlemire** [comment]
Hi Hannes, i added some internal posts already to the document: https://docs.google.com/document/d/1X4DYhO2IbLm5xPgP-oNwKEZV6q2dRySb/edit
Do you want to review them and give me your feedback?

Moreover, are more cards still needed? 
I saw that a lot more has been added since my holiday. 

I want to work further on the other things in this and next week so i will keep you updated with that later on.

**Comment by hannesdatta** [comment]
We retire this issue! Socials are all active. Open separate issues for feedback if necessary.
