### ISSUE TITLE
[Development Call]: Script that converts .Rmd/Jupyter notebooks to TSH format

### ISSUE THREAD

**Issue by shrabasteebanerjee** [tilburgsciencehub/website#675]
### Is your content request related to a problem you've encountered during your research process? Please describe.

Some folks are more comfortable writing on Rmd or Jupyter. Can we offer them the option of using a script that takes their markdown as input and generates the TSH template as output?

**Comment by hannesdatta** [comment]
Here are some pointers, @paulina-ambroziak.

https://hugodown.r-lib.org/

I'd say: teach yourself how this package works and what it can do (and cannot do). Maybe we can use it as requested.

**Comment by paulina-ambroziak** [comment]
Hi @hannesdatta,

I'd like to have a short discussion to choose the best solution, some points for the meeting:

**1.	Hugodown and Blogdown**
hugodown is an experimental package – there’s not much documentation available
blogdown might be more intuitive to use due to addins in RStudio (e.g. _Addins > Blogdown > New post_), Preview site with _blogdown::serve_site()_
Info on using blogdown: https://smac-group.github.io/ds/section-blogdown-websites-and-blogs-creation.html 

**2.	Hugo Archetypes**
It is possible to create Archetypes in Hugo so that when a new post is created (with ‘_hugo new_’ command), it contains a template (e.g. for a building block or tutorial).
More info: https://gohugo.io/content-management/archetypes/ 

**3.	Convert Rmd to md**
It’s recommended to convert RMarkdown files directly to Markdown without Blogdown by using _render("input.Rmd", md_document())_ or adding _output: md_document_ to the file’s front matter.
Source: https://wowchemy.com/docs/import/rmarkdown/ 

**4.	Convert Jupyter Notebook to md**
Convert notebook to Markdown:
_jupyter nbconvert Untitled.ipynb --to markdown --NbConvertApp.output_files_dir=._
Source: https://wowchemy.com/docs/import/jupyter/

**Comment by paulina-ambroziak** [comment]
Notes after speaking to Valerie:

- .md format is not an issue
- the main issue was to find the template for writing the building blocks or tutorials (we have them [here](https://tilburgsciencehub.com/tutorials/more-tutorials/contribute-to-tilburg-science-hub/pullrequests/) but it is not easy to find)
-  problems with the text formatting (e.g. how to highlight text as a summary, example, warning or tip) were due to difficulties with finding the template
- it is not clear how to fill in e.g. aliases
- lack of instruction on how to preview the website locally (with _hugo server_)
- not clear process of opening a pull request on GitHub

**Solution:** update Onboarding Guide with a step-by-step guide explaining everything from creating a building block/tutorial from a template (including templates that can be downloaded in the .md format) to building the site locally to creating a pull request.

**Comment by paulina-ambroziak** [comment]
Notes after talking to Alex:
- the benefit of Rmd over md is that you can run a chunk of code and print the output
- so instead of running the code locally and saving the screenshots, the outputs are generated automatically on the website
- Alex has implemented it on his personal website, where the Rmd generates the output files and the HTML file

**Action Point:** research how to implement it on the TSH website

**Comment by hannesdatta** [comment]
Let's close. We didn't end up taking this route for TSH.
