### ISSUE TITLE
make ALL the links in the breadcrumb trails to work

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/website#75]
Currently some of them link to a 404. Just point to the relevant building block, tutorials or example overview page, possibly using anchor (#) links so that the user lands at the appropriate "height".

![image](https://user-images.githubusercontent.com/50109671/105824389-90a3a200-5fbe-11eb-9d09-022657ce2ea0.png)

**Comment by heyarviind** [comment]
can you make all the overview pages to index.md file? because this makes sense that this is the entry page and it also solves this issue. I have changed the name of the file for the same...

let me know if this works for you

**Comment by andreantonacci** [comment]
Hi Arvind, not all the breadcrumb links work yet. I see your point in renaming the entry pages as index.md in tutorials, but as I told you that would break the overview pages. Can you please find a solution?

**Comment by andreantonacci** [comment]
Renaming an entry page as index.md has these 2 side effects:
1. Not all the tutorial pages are shown on the overview page
![Screenshot 2021-01-27 at 14 27 23](https://user-images.githubusercontent.com/50109671/105997518-fe79c780-60ab-11eb-9f50-9e5344bf431f.png)

2. The navigation inside the tutorial is broken too, since you can only see the entry page on the left menu.
![image](https://user-images.githubusercontent.com/50109671/105997612-1a7d6900-60ac-11eb-8f08-4c8568efb20b.png)

**Comment by heyarviind** [comment]
you can test it now

**Comment by andreantonacci** [comment]
Hi Arvind,

I'm reopening this because we noticed that there's a problem with the breadcrum trails for tutorials (the ones for building blocks seem to work fine).

Clicking on the second to last level ("Practicing Pipeline Automation Make", in this case) yields a 404 page.
![Screenshot 2021-06-21 at 09 59 04](https://user-images.githubusercontent.com/50109671/122727648-8b9a0480-d277-11eb-8892-a20454937fdf.png)

https://tilburgsciencehub.com/tutorials/reproducible-research/practicing-pipeline-automation-make/overview/

Can you please fix it? Thanks

**Comment by heyarviind** [comment]
Hey Andrea, this issue and https://github.com/tilburgsciencehub/website/issues/106 are related.

It is happening because each hierarchy should have an index.md or _index.md file. I know it would hide the other pages but this is the only solution I can come up with if you want to make the breadcrumbs work for sub levels.

**Comment by andreantonacci** [comment]
Fine Arvind. Does this mean that it would hide the tutorials subpages from the overview page (https://tilburgsciencehub.com/tutorials/) or also somewhere else? Please, try to implement this on the staging branch so we can test it, thanks.

**Comment by heyarviind** [comment]
Hey can you test this https://github.com/tilburgsciencehub/website/pull/175, I have added a _index.md file. With this, the breadcrumbs work but it created its own section as you can see on https://tilburgsciencehub.com/tutorials/reproducible-research/practicing-pipeline-automation-make/

this is something I am hating about Hugo rn. also this issue is related to #106 

Maybe I am missing something here, need to ask this in Hugo's forum for better clarity.

**Comment by andreantonacci** [comment]
Hi Arvind, did you hear back from the Hugo forum already?

**Comment by andreantonacci** [comment]
e602568
