### ISSUE TITLE
"weird", non-public tags and names / breadcrumbs

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#765]
I noticed our site displays several internal names that look very amateurish.

For example, the breadcrumb trail lists "ChatGPT article" and the very rudimentary title "chatgpt research".

<img width="568" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/2dc7ddcb-04e3-4b82-96f9-9d820ca804b2">

The same thing happens in our search dropdown:

<img width="352" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/49070ac4-2c6c-41a8-aa66-8e6b054e5e09">

Can you please come up with suggestions to fix this? Is this something we want to fix in the `.md` files? Or is this something we ideally solve via some code?

If for the .md files: make clear instructions how to do this and assign an RA for improving these titles on all of our sites. If programming solution: implement it, please.

**Comment by thierrylahaije** [comment]
For the popular pages and the last part of the breadcrumb (the title of the single .md). The second last part of the breadcrumbs will be a little more difficult, since the variable needed for this is not directly passed on. I need to do more research for this.

Tasklist:

- [ ] Fix Title
- [ ] Fix Popular Pages
- [ ] Fix Second Last Breadcrumb

**Comment by hannesdatta** [comment]
Still some work to do to fix the breadcrumbs; ideally take it from title of the `.md` files.

**Comment by thierrylahaije** [comment]
I checked the complete breadcrumbs and where the exact errors were in the title. I found out that the remaining problem was in the fact that some sub-categories in the building blocks have url titles that do not match the displayed in the menu. 

To fix the second last breadcrumb, I created a separate issue (issue #790 ), since this has to do with restructuring the folder structure which might be more efficient to do when all pull requests have been processed.
