### ISSUE TITLE
reduce splash/landing page banner

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#768]
With our improved landing page, we have a bunch of content to offer. Yet, kind of only show our logo above the fold, see screenshot below.

<img width="1391" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/6e12e2cd-83ad-4019-99fb-ffb5d5227167">

Can you suggest ways to change that? E.g., reducing the size of the logo and links to the tour page, dropping the logo altogether, moving it down? some other ideas? I want to make the point quicker about our content. E.g., reddit doesn't say what they are. they just show their content...

Thanks!

**Comment by thierrylahaije** [comment]
My recommendations to decrease the height of the banner would be as follows:

- Remove the New to Tilburg Science Hub Title (seems unnecessary to me)
- Put the buttons horizontally instead of vertically. Also update the colors of one of the buttons (primary and secondary color) to create a clearer difference. This is common practice, normally sites do not use two buttons with the exact same styling next to each other.
- Edit the image to make it less high but wider. 
- If necessary, let the banner use the full container width.

In the end this will not put all content straight into sight, but at least the first row of blocks and maybe a little more. Comparing TSH with reddit or youtube or something like that cannot be done in this case, since their brand identity is so well known that they just need to display the content (everybody knows what reddit is and how it works) instead of also adding additional text to attract and inform people as a normal business would do (using a banner for example, as TSH does). I think that when we decrease height the banner, a lot of people will scroll down to see the rest of the content.

I would personally advise to do an A/B-test to check whether minimizing the banner has an impact on how many people view the full cards block.

**Comment by hannesdatta** [comment]
I love the suggestions.

I would do this (mock up):

![image](https://github.com/tilburgsciencehub/website/assets/16557730/73f78420-4904-4132-9911-cbcdb83105fc)

- only one action: take the tour
- make banner horizontal rather than vertical 

This will put the cards up a little higher. good enough i guess.

No need to A/B test this.  

Do you have access to the image files?

**Comment by thierrylahaije** [comment]
I have created an adjusted version of the banner:

<img width="1423" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/1894940c-db1d-4c49-b7ce-36dae8a9265c">

If you like this version, I will push it.

**Comment by hannesdatta** [comment]
Push please! Looks good!

**Comment by thierrylahaije** [comment]
Issue is fixed so will be closed.
