### ISSUE TITLE
add reading time estimate?

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#773]
Just came across this page:

https://www.deployhq.com/git

We could consider adding (automatically generated) reading time/work-through time estimates for our content. Maybe it makes everything look a little less daunting/easy to get started?

**Comment by thierrylahaije** [comment]
Great idea, this will definitely tempt students quicker (since I think they would like to know how much time something takes to do. Automatically generated is maybe not the best idea, since this could easily be added as a variable in the top of an .md, which then can be retrieved by Hugo to be displayed.

**Comment by thierrylahaije** [comment]
Hi @hannesdatta,

As an example, I implemented the reading time for the building blocks (added it as development branch), let me know what you think about it. I have 2 further questions to finish it up:

- Do you want to add it for all content (tutorials, examples & building-blocks)
- If you also want it for tutorials, do we want to calculate the total tutorial time, or per sub part of a tutorial?

**Comment by thierrylahaije** [comment]
I fixed this issue. Reading times are now live.
