### ISSUE TITLE
Find ways to get previous users back to the website 

### ISSUE THREAD

**Issue by fleurlemire** [tilburgsciencehub/website#793]
Background

We're super depending on google (94% of our traffic is organic search). Maybe find ways to get previous users back to our site. Maybe google analytics helps you find some sweet spots.

**Deliverable**
- Come up with a plan on how to get the users back with multiple proposals

**Comment by thierrylahaije** [comment]
Hi Fleur, 

I just saw this issue, and since I already have experience with retrieving previous users, I had some ideas to get users back to our site.

- Email Marketing:
Build and maintain an email subscriber list. Send out regular newsletters and updates to remind users about our website's content. Maybe personalize emails based on user preferences and behavior.

- Retargeting Ads:
Implement retargeting or remarketing ads. These ads target users who have previously visited our website. We can show them relevant ads across various online platforms. The ads could be based on what users have previously read (e.g. a users who read about reproducible work will probably be attracted more easily to an article within that category).

- Create contests:
Contests can be enticing reasons for users to revisit your website and engage with oour content.

- Personalization:
Implement personalization features on our website. Tailor content recommendations based on users' past interactions to make their experience more relevant and engaging.

**Comment by hannesdatta** [comment]
Let's follow up with email marketing.

__Deliverables:__
- @hannesdatta gives you access to an email marketing system
- where to collect email address on the site / "how"? use a list for initaliziation?
