### ISSUE TITLE
[Development Call]: New TSH merchandise

### ISSUE THREAD

**Issue by valerievossen** [tilburgsciencehub/website#842]
### Is your content request related to a problem you've encountered during your research process? Please describe.

It could be nice to have TSH merchandise, to promote the platform and open science in general around university and other places! I was thinking laptop stickers, but (depending on the budget) we could make other stuff, like t-shirts, pens etcetera? 

@kleintob, since you organised the coffee mugs, what do you think of this idea?
When we know which products we want, we can think of the design and how to produce them. @fleurlemire, do you want to help with this?

### Would you like this to be a Building Block or a Tutorial?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fleurlemire** [comment]
Yes, good idea, I want to help! To me, laptop stickers sound like a really good idea since other students or colleagues can also see these on your laptops so it can really work to make people aware of us and promote us. I also think pens could be a really good idea! People exchange pens if others forget it, and use pens a lot, so i think this works the same with awareness!

**Comment by kleintob** [comment]
I think it’s a good idea to produce more THS branded stuff.
For the mugs, what we’ve learned (I think) is that we need to make the logo smaller. One cannot read the text without turning the mug. So maybe smaller and twice, once on each side.
Laptop stickers sound nice, and pens, too (nice ones that don’t feel cheap). I’m a bit less enthusiastic about T-Shirts. When would we wear those T-Shirts? It’s less of an everyday item I’d say.

t

From: valerievossen ***@***.***>
Date: Monday, 4 September 2023 at 17:11
To: tilburgsciencehub/website ***@***.***>
Cc: Tobias Klein ***@***.***>, Mention ***@***.***>
Subject: [tilburgsciencehub/website] [Development Call]: New TSH merchandise (Issue #842)
Contact Details

No response

Is your content request related to a problem you've encountered during your research process? Please describe.

It could be nice to have TSH merchandise, to promote the platform and open science in general around university and other places! I was thinking laptop stickers, but (depending on the budget) we could make other stuff, like t-shirts, pens etcetera?

@kleintob<https://github.com/kleintob>, since you organised the coffee mugs, what do you think of this idea?
When we know which products we want, we can think of the design and how to produce them. @fleurlemire<https://github.com/fleurlemire>, do you want to help with this?

Additional context

No response

Would you like this to be a Building Block or a Tutorial?

None

Purpose

No response

Motivation

No response

Suggested title

No response

Suggested keywords

No response

Required tools

No response

References

No response

Code of Conduct

  *   I agree to follow this project's Code of Conduct

**Comment by fleurlemire** [comment]
Do you want to continue with this or put this on hold since logo is changing probably and continue when that has changed? @hannesdatta

**Comment by hannesdatta** [comment]
@Lisa-Holling - let's follow up, also given last week's discussion in the WOW.

**Comment by kleintob** [comment]
Not so sure I like the logo you propose, sorry.

I think the old wide logo is actually fine, maybe we can make it smaller and put it twice next to one another.

In a way I even like the mugs as they were, people who know will know. And it makes people wonder which is not per se bad.

I’d vote to keep it. But I’m open to more suggestions too of course.

Please in any case also make more of the mugs we already had.




On Mar 7, 2024, at 14:47, Lisa Holling ***@***.***> wrote:

﻿

@hannesdatta<https://github.com/hannesdatta>
Discussed with Francisco as well, some good options are:

  *   laptop stickers
  *   pens
  *   doppers (water bottles)
  *   coffee to go mugs
The problem Tobi mentioned earlier holds for everything but the pens, because the logo is really wide.
Can we do anything about this? E.g.
image.png (view on web)<https://github.com/tilburgsciencehub/website/assets/123000727/0f7cdad4-6ab4-4ab9-a272-67c8a88de7ec>
This would look really nice on a Dopper!!

Will look more into the specifics next week

**Comment by Lisa-Holling** [comment]
[merch.docx](https://github.com/tilburgsciencehub/website/files/14551350/merch.docx)
Some ideas. There are thousands of options, so let me know if you had something else in mind.

**Comment by kleintob** [comment]
This looks already very good.

My two cents: I think white pens would be nicer (no wood), if possible high quality. Too many low quality pens for my take. Maybe something like this: https://www.drukwerkdeal.nl/nl/producten/pennen/foer

Regarding the to-go cups, maybe order them somewhere else: https://eventgoodz.nl/product-categorie/koffiebekers-to-go-bedrukken/
Question is here what we want. I personally like the “keramische” ones, but one cannot close them and put them into one’s backpack
But the ones that can go into a backpack are really expensive generally, so maybe we don’t want that anyway




From: Lisa Holling ***@***.***>
Date: Sunday, 10 March 2024 at 19:25
To: tilburgsciencehub/website ***@***.***>
Cc: Tobias Klein ***@***.***>, Mention ***@***.***>
Subject: Re: [tilburgsciencehub/website] [Development Call]: New TSH merchandise (Issue #842)

merch.docx<https://github.com/tilburgsciencehub/website/files/14551350/merch.docx>
Some ideas. There are thousands of options, so let me know if you had something else in mind.

**Comment by kleintob** [comment]
Just a thought regarding quantities:

maybe we want 100 pens, 30 or so mugs, 100 stickers, and I’m not sure about the to-go cups. Maybe 10 or 20 for a start? I think in a normal work environment the normal mugs are preferred and used more often

then we could use the pens and stickers for events




From: Lisa Holling ***@***.***>
Date: Sunday, 10 March 2024 at 19:25
To: tilburgsciencehub/website ***@***.***>
Cc: kleintob ***@***.***>, Mention ***@***.***>
Subject: Re: [tilburgsciencehub/website] [Development Call]: New TSH merchandise (Issue #842)

merch.docx<https://github.com/tilburgsciencehub/website/files/14551350/merch.docx>
Some ideas. There are thousands of options, so let me know if you had something else in mind.

**Comment by Lisa-Holling** [comment]
@kleintob 

**Pens**
Those pens are great! We can do the light blue colour (matches with the logo), or otherwise I would suggest orange or black. For 100 pens the price would be €213,18 

**Stickers** 
100 stickers 35 x 105 mm would be €38,12. There is also an option for a slightly other type (Full color offset instead of Full color digital) which is €31,21 for 250 pieces (more for less is always better right?!)

**Mugs**
For the [mugs](https://eventgoodz.nl/product/mok-piton-wit-350ml/), the smallest amount is 50 pieces for €395. If we only want 30, I can look for another website. 

**Coffee to go**
I think it is better to have ones that you can close, like [these](https://eventgoodz.nl/product/koffiebeker-to-go-lille-350ml/). For 25 pieces in white with our logo, the price would be €299,75.

Then in total, the merch would be:
(1) On drukwerkdeal.nl
![image](https://github.com/tilburgsciencehub/website/assets/123000727/2a94ba67-414f-434d-a40c-cac8b5ed306d)

(2) On eventgoodz.nl
![image](https://github.com/tilburgsciencehub/website/assets/123000727/f30aa798-5cca-49cc-b05f-08b3d82d6c91)

**Comment by kleintob** [comment]
Looks all good to me.
50 mugs seems fine, plus 25 of the to go coffee cups that you suggest.
For the pens please make sure the color is either very similar or very different. Somewhat similar is not so good. Our logo is dark blue, so why not dark blue?
Finally could you please share again the link to the logo file that you would use, just to double check? I personally like the wide one.

**Comment by Lisa-Holling** [comment]
@kleintob 
find the logo attached.
![TSH - UNIVERSITY COLORS](https://github.com/tilburgsciencehub/website/assets/123000727/d6542bf7-d991-4214-955c-ba8228d3ec1c)


The blue in the logo is right between the two blue colors they have, but I think they would both be good. 
Anyways, you can choose between these colors:
![image](https://github.com/tilburgsciencehub/website/assets/123000727/4dcc66f5-fb13-4574-8daa-8374c9f8049b)

**Comment by kleintob** [comment]
This all looks very good. Thanks!

I’d say let’s go for light blue. With a bit of luck, this will fit well.

So I’d say let’s order.

Have you talked with Hannes or anyone else about practicalities?

If not and if you need an address/destination, then you can put my name and office number:

Tobias Klein
Tilburg University
Department of Econometrics and OR
Warandelaan 2
5037 AB Tilburg

Do they do this with an invoice, or do they need payment upfront? If so let me know. Then we can see how we can best do that.
