### ISSUE TITLE
[Update request]: Edit formatting and add content for the BB 'Learn Python and Jula

### ISSUE THREAD

**Issue by Aakriti-G** [tilburgsciencehub/website#843]
**Background**

The building block 'Learn Python and Julia' mainly consists of links to tutorials and other information sources which does not seem to align with the format of the TSH website. Fixing this issue could entail summarizing the content on these links, preferably over a few additional BBs to have a better structure for the website. This change appears to be a bit out of scope of the Summer Sprint (see issue #740) and therefore I am adding a new issue for this :)

**What needs to be updated?**
Content structure for the building block [Learn Python and Julia](https://tilburgsciencehub.com/building-blocks/develop-your-research-skills/learn-to-code/learn-python-and-julia/)

__Deadline__

TBD

**Comment by valerievossen** [comment]
I would like to work on this during the christmas break/january!

**Comment by hannesdatta** [comment]
Hi Valerie,
can you devise a list of useful building blocks to work on? I like the idea a lot!

**Comment by valerievossen** [comment]
Yes, will do! Will probably be around the beginning of January.

**Comment by valerievossen** [comment]
Hi @hannesdatta, 

I thought about it, and came up with dividing the Python content into the following topics:
1) Python basics: small code examples of data types, variables, loops, functions, boolean logic etc.
2) Python coding style guidelines: extend the one that's already have with code examples (like the R coding style guidelines), instead of just links to other resources
3) Install Python packages (is already there)
4) Pandas for data analysis in Python
5) Numpy for numerical calculations in Python
6) Matplotlib for data visualisation in Python

Let me know what you think!
