### ISSUE TITLE
Netlify deploy preview doesn’t show images 

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#871]
### Contact Details

h.datta@tilburguniversity.edu

### What happened?

I noticed that all the deploy previews generated for PRs do not show any image. For example, the icons in the header bar are missing, and so are other images. This makes the deploy preview look broken. Can you please investigate why these pics do not render and suggest a fix?

### To reproduce

Create a new PR and visit the deploy preview via the Netlify link in the PR on GitHub.

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thierrylahaije** [comment]
Currently it is even worse. I can't even see the stylesheet in the deploy preview, but I don't understand why it does not include the stylesheet. I need to investigate this more thoroughly.

**Comment by hannesdatta** [comment]
Thanks for looking into it!

**Comment by thierrylahaije** [comment]
@hannesdatta Could you provide me (via mail) with the Netlify logs and a screenshot of the Netlify Build Settings? This might give some indication to why the styling is not applied (since it is only not working in the preview).

**Comment by hannesdatta** [comment]
Check your email - I sent you an invite to Netlify to ur Tilburguniversity address!

**Comment by thierrylahaije** [comment]
@hannesdatta It is very hard to find out the exact problem. When looking through the preview, I saw that the normal images where added, but that the icomoon icons (a font which we import in scss) is not added, meaning it all has to do with styling. The only conclusion I have is that currently, the scss to css compiler is not functioning correctly for the builds. Why this happens is something I don't know, since I have very little experience with Netlify to give an exact conclusion. Even Google and ChatGPT don't offer any help. 

The only thing we might possibly try is adding sass to the command in the build settings (it currently says 'hugo' only). The sass command provides instructions for netlify to force compiling the .css files. But, this is just a guess and no definitive answer. It might be wise to make a ticket for support on Netlify and ask them or the original developer what the issues might be.

**Comment by hannesdatta** [comment]
Trying to implement this advice: https://discourse.gohugo.io/t/css-does-not-show-up-on-deployed-netlify-site/34525/6

We also have a `public` folder committed (which is very old). So, maybe this is why the site doesn't render.

**Comment by hannesdatta** [comment]
@thierrylahaije  - can you take it up again? i fixed the stuff that the CSS wasn't loaded (we wrongly had committed the "public" folder). After fixing, the deploy previews on NEW PRs look good - except that the images still do not render.
