### ISSUE TITLE
allow multiple authors, deprecate authorlinks

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#892]
- [x] We need a feature allowing MULTIPLE authors to be tagged to our content. Can you please implement?

<img width="448" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/39f226e1-e297-4ae4-927d-71d7fea7937f">

Just comma separating didn't seem to work for me (treated as one name)

<img width="333" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/81610512-05f6-452e-911a-e772d87cf33b">

- [ ] We also need to consistently LINK back to our contributor page and NOT use the authorlink provided in the original `.md`. 
 
 I imagine this could be tricky. For example, Diego has three names, but his `.md` file in the contributor profile looks different.

"Diego Sanchez Perez" --> diegosanchez.

Probably best to have usernames (`diegosanche`) and actual/display names (Diego Sanchez Perez).

- [ ] When done, update instructions on how to link contributions to contributor page.

__Let me know if you have any questions.__

**Comment by thierrylahaije** [comment]
- I fixed the first item, you can now just add multiple authors with comma separation.
- For the second item, it seems that what you want is more "dynamic" (we would need to fetch a username on page when author is added), which in Hugo is almost impossible. I think for now, for example Diego could just name his .md as diegosanchezperez.md, then he can use his full name. This would be something we could change in the Flask website because this is dynamic.

**Comment by hannesdatta** [comment]
It's not as hard as it sounds.

On each building block, we already provide short links (e.g., get/python).

All we need is a meta line called /user/thierrylahaije in the contributors md file, and then the author name on an md content file becomes user/thierrylhaije.

That's it, right? It wall establish the goal of having usernames and being able to link through properly.

Check please whether you can implement it?

I don't want to stall all layout and technical issues before Flask is ready. I hope you understand.
