### ISSUE TITLE
profile pics loading time

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#893]
The profile pics take forever to load.

Is there a way to store the original ones but auto-compress / downsize them when the site is built for production?

**Comment by thierrylahaije** [comment]
I tried so many possibilities but I could simply not fix it. There are ways explained by Hugo to convert images (https://gohugo.io/content-management/image-processing/#quality), but for some reason which I cannot find out, it does not work well with variables. I could not find any discussion online that provided a solution for the error I kept receiving. 

The best and easiest solution is by just manually converting them, or, we could create a python script for this? Since in Hugo itself will be very difficult.

**Comment by hannesdatta** [comment]
Just reformat pics to a manageable size manually please. Further, provide instructions how to compress images / scale images in onboarding guide or provide max file size (eg 150kb in jpg or png). Choose something that makes sense here.

**Comment by thierrylahaije** [comment]
@hannesdatta instead of scaling, I would advise to convert the images to webp images (which is the common standard for small qualityloss pictures by google). This will not decrease the dimensions, only the size. We should try to avoid the use of .png and .jpg as much as possible. Shall I convert the contributors images to webp?
