### ISSUE TITLE
loading time with local builds

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#899]
I'm currently working locally on a really bad internet connection and realize that locally building our site still loads a tremendous amount of scripts online. So, in other words, even though I'm working locally, things take forever.

This let me think about whether we load scripts/external components efficiently on the site. Do we use lazy loading, such as for the fonts? Is there anything else that we can improve so the site also builds and works when looking at it locally? This may have positive consequences on our online site as well (I think...).

Let me know!

**Comment by hannesdatta** [comment]
--> investigate whether we have lazy loading.

**Comment by thierrylahaije** [comment]
I investigated our loading times to check whether lazy loading would have a real effect. Below the current speed results:

<img width="1175" alt="image" src="https://github.com/tilburgsciencehub/website/assets/65568251/702d31e1-ae71-40a6-af1f-8a014a325212">

As you see our site is already really fast (above standard, standard fcp is about 1,5-1,8s, cp around 2s) for loading times. I can defer the font awesome script if you want, but this will not have a major effect on the speed and might impact the visual structure since we use bootstrap columns. Other scripts/css are either critical or are very small in download time.

**Comment by hannesdatta** [comment]
Alirght. Looks good.
