### ISSUE TITLE
click on tour doesn't work

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#930]
When clicking on tour here,

![image](https://github.com/tilburgsciencehub/website/assets/16557730/75ce1db3-2563-433a-ab9b-fbf9962dad5b)

the tour doesn't start.

Can you fix this?

**Comment by thierrylahaije** [comment]
@hannesdatta I checked the website and it worked for me. Can you check again on the live website when you refreshed your cache? If it is still not working at your pc, please let me know which type (desktop/tablet/mobile) and which browser you used, because that would mean it is a browser-specific issue

**Comment by hannesdatta** [comment]
Reduce time before tour shows
