### ISSUE TITLE
[Bug]: New blog post is not visible and keeps loading on website

### ISSUE THREAD

**Issue by fleurlemire** [tilburgsciencehub/website#945]
### What happened?

A new blog post has been added today, but is not loading on the website: 
![Schermafbeelding 2023-10-11 om 15 45 12](https://github.com/tilburgsciencehub/website/assets/122876103/6ccfa777-8334-4394-8176-91e190da2fd8)
It is about this one: https://tilburgsciencehub.com/blog/toss_presentation/

However, all of the other blogs are loading: https://tilburgsciencehub.com/blog/
The main difference between those posts, is that this one has an attachement of a pptx file. I think it might go wrong there but i am not sure. 

Does anyone know how to fix this? @thierrylahaije do you have any idea maybe?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thierrylahaije** [comment]
@fleurlemire I fixed the problem. The issue was in the alias:

> aliases:
>   - /blog/TOSS_presentation
> 

remember to only use lowercase in the alias, since the alias is used in the Hugo link structure. Links do not distinct between capitals and lower case, which leads to the problem that it keeps trying to reload. After a while, the Netlify protector kicks in, because it has the idea your are executing a possible DOS attack. That is why you got the white screen.
