### ISSUE TITLE
fixing layout for new 4-layer hierarchy

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#990]
Hi @thierrylahaije,

In #989, @NielsRahder has implemented our new, four-level hierarchy. I have also collapsed our menu to "topics".

I need your attention to the following issues:

1) Please make all menu items in the new menu clickable. I want them to lead to LIST 1 (see below) when clicked on layer 1, and to LIST 2 when clicked on layer 2 (see below).

<img width="611" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/55ffd113-0360-491d-9fcc-739d406ab9e1">

2) "LIST 1" overview

When clicked on LIST 1 header in the menu, I want a list to appear that looks like this. However, this menu needs to display layers 2-4 of our hierarchy, NOT layers 1-3 (as it does right now). In terms of layout, this corresponds to how the building block section looks like at TSH right now.

<img width="1155" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/9a4f3cad-e5c5-4ed1-a9f5-64db1d2a55fb">

At the end of the list at layer 4, I want you to display a max. number of items (say, 10), and also show a SHOW MORE button. This leads to LIST 2.

3) "LIST 2" overview

The list 2 overview shows the richness at the lowest level of our hierarchy, level 4. Please implement what used to be our tutorial section here.

<img width="1097" alt="image" src="https://github.com/tilburgsciencehub/website/assets/16557730/f929b650-f9e0-47ff-a59f-6ad0c19bfd06">

4) Ensure that the mobile and desktop menus work accordingly.

5) Fix any broken links on our landing page.

6) Rename what remains either `/tutorials/` or `/buildingl-blocks/` on our content folder to `/topics`.

Can you try giving this utmost priority? I would love to open up the site for new PRs, but that requires us to have published the new structure.

From there, we can see how it goes, implement these changes in Flask as well, and then prepare for the launch of Flask.

**Comment by thierrylahaije** [comment]
@hannesdatta I fixed the layout, but there are still a couple of things we need discuss, because I am unsure if I did exactly what you wanted. Let's meet sometime tomorrow. 

@NielsRahder to make sure everything works, we still need to adjust some things:

- [ ] make sure there are no 5th levels (getting-started-with-r, getting-started-with-stata)
- [ ] Folder names 
  - [ ] All _ in folder names should be - 
  - [ ] No capitals unless necessary (e.g. Python RStudio), 
  - [ ] so e.g. 
      - [ ] Document_creation should be document-creation
      - [ ] Develop_coding_skills should be develop-coding-skills
- [ ] All 3rd level _index.md files should have a parameter type added with value subcategory. You can just copy this text (type: subcategory) and then add this to each of the 3rd level _index.md’s. (e.g. in IDE, Python, Stata, I already fixed them so you can check these out as an example)

**Comment by NielsRahder** [comment]
I’ve adjusted the points Thierry mentioned and added them to the branch `final-fix-niels` on my repo. 

For the issue concerning the 5th hierarchy, I adjusted a number of files so that they now render properly. However, for a few old tutorials that contain numerous files (see Google Docs) I wanted your opinion @hannesdatta, as we can combine these files from the tutorial into one large piece of content. Or we can keep them as numerous individual pieces, and link them together.

LMKWYT!

**Comment by thierrylahaije** [comment]
@hannesdatta the update is now available in the development branch final-fix-niels. I worked through the menu and all layers are now functional. I only need the following to fix the last details:

- [ ] The updated version of service_account.json, only then I can fix the popular pages and cards Python script. I tried it with the basic API key, but this did not work. Currently, the cards.json is fixed manually.
- [ ] We need to check whether Algolia Search works when it gets pushed. Can we use some sub domain to link to the development branch in Netlify? 
- [ ] In the development branch, we still need to do some checks to see if everything is working as expected.
